#Predefine exception

'''
file=open("a1112223.txt","r")
file.close()
# this a.txt is not presently 

with open ("filename.txt","r") as fileobject:
    do operation. 



div=100/0




'''
#  User define Exception Handling


try:
    num=10
    num2=20

    divd=10/num2
    num3div=100/0
    print("last line of try block,",divd)

except:
    print("there is zero in denominator.")



'''
def functionname():
    jljkjlj
    lljljlkjlj


class classname(object):
    def function1( a, b):
        pass





obj1=classname()
obj1.function1(a=12,b=34)

'''

    

